"""timestamped_model

Revision ID: 148330712a84
Revises: 5ede7bdac949
Create Date: 2024-12-27 14:45:11.895501

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "148330712a84"
down_revision: str | None = "5ede7bdac949"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("abi", sa.Column("created", sa.DateTime(), nullable=False))
    op.add_column("abi", sa.Column("modified", sa.DateTime(), nullable=False))
    op.add_column("contract", sa.Column("created", sa.DateTime(), nullable=False))
    op.add_column("contract", sa.Column("modified", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contract", "modified")
    op.drop_column("contract", "created")
    op.drop_column("abi", "modified")
    op.drop_column("abi", "created")
    # ### end Alembic commands ###
