"""abi_json_not_null

Revision ID: 1737a3c2c89d
Revises: a4f3b2c1d8e9
Create Date: 2026-06-08 08:22:33.173747

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1737a3c2c89d"
down_revision: str | None = "a4f3b2c1d8e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Match both SQL NULL and the JSON `null` scalar ('null'::json). Rows written
    # through the old `Column(JSON)` mapping (without none_as_null=True) serialised
    # Python None as JSON null, which `abi_json IS NULL` does not match.
    op.execute(
        "UPDATE contract SET abi_id = NULL "
        "WHERE abi_id IN (SELECT id FROM abi WHERE abi_json IS NULL OR abi_json::jsonb = 'null'::jsonb)"
    )
    op.execute(
        "DELETE FROM abi WHERE abi_json IS NULL OR abi_json::jsonb = 'null'::jsonb"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "abi",
        "abi_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "abi",
        "abi_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###
