"""Add index for abi relevance field

Revision ID: 66c1eb4456de
Revises: b062e814dbea
Create Date: 2025-05-22 13:35:44.778770

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66c1eb4456de"
down_revision: Union[str, None] = "b062e814dbea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_abi_relevance"), "abi", ["relevance"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_abi_relevance"), table_name="abi")
    # ### end Alembic commands ###
