"""Add index for created field

Revision ID: b062e814dbea
Revises: e5e94343c151
Create Date: 2025-01-30 16:44:47.987365

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b062e814dbea"
down_revision: Union[str, None] = "e5e94343c151"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_abi_created"), "abi", ["created"], unique=False)
    op.create_index(op.f("ix_contract_created"), "contract", ["created"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contract_created"), table_name="contract")
    op.drop_index(op.f("ix_abi_created"), table_name="abi")
    # ### end Alembic commands ###
