"""init

Revision ID: c52699d26409
Revises:
Create Date: 2024-12-11 10:58:44.921603

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c52699d26409"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abisource",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chain",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "abi",
        sa.Column("abi_hash", sa.LargeBinary(), nullable=False),
        sa.Column("relevance", sa.Integer(), nullable=False),
        sa.Column("abi_json", sa.JSON(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["abisource.id"],
        ),
        sa.PrimaryKeyConstraint("abi_hash"),
    )
    op.create_table(
        "contract",
        sa.Column("address", sa.LargeBinary(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trusted_for_delegate", sa.Boolean(), nullable=False),
        sa.Column("proxy", sa.Boolean(), nullable=False),
        sa.Column("fetch_retries", sa.Integer(), nullable=False),
        sa.Column("abi_id", sa.LargeBinary(), nullable=True),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["abi_id"],
            ["abi.abi_hash"],
        ),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chain.id"],
        ),
        sa.PrimaryKeyConstraint("address"),
        sa.UniqueConstraint("address", "chain_id", name="address_chain_unique"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contract")
    op.drop_table("abi")
    op.drop_table("chain")
    op.drop_table("abisource")
    # ### end Alembic commands ###
