"""nullable contract name

Revision ID: e4e2e62601d2
Revises: a160a84ce491
Create Date: 2025-01-02 17:02:58.232426

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4e2e62601d2"
down_revision: str | None = "a160a84ce491"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("contract", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("contract", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
